# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile
tasks:
  - name: "set env"
    env:
      PIP_USER: false
  - name: "install dependencies"
    init: poetry install
  - name: start liveserver  
    command: poetry run invoke livereload
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8001
    onOpen: open-preview
