# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile
tasks:
  - name: "install dependencies and start live server"
    env:
      PIP_USER: false
      POETRY_VIRTUALENVS_PATH: /workspace/virtualenvs
    before: eval $(gp env -e)
    init: |
      poetry install 
      mkdir -p /workspace/bin
      export PATH=$PATH:/workspace/bin
      curl -o /workspace/bin/stork https://files.stork-search.net/releases/v1.4.0/stork-ubuntu-20-04
      chmod +x /workspace/bin/stork
    command: poetry run invoke livereload
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8001
    onOpen: open-preview
