image: python:3.11-bullseye

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - pip install pdm
  - pdm sync --prod
  - curl -o /usr/local/bin/stork https://files.stork-search.net/releases/v1.6.0/stork-ubuntu-20-04
  - chmod +x /usr/local/bin/stork

build-test:
  script:
    - pdm run invoke build
  except:
    - main

build-publish:
  script:
    - pdm run invoke publish
  artifacts:
    paths:
      - public/
  only:
    - main

deploy:
  variables:
    GIT_STRATEGY: none
  before_script:
    - rclone config create scaleway-ams s3 provider=Scaleway env_auth=true region=nl-ams endpoint=s3.nl-ams.scw.cloud
  image:
    name: rclone/rclone:1
    entrypoint: [""]
  needs:
    - build-publish
  stage: deploy
  script:
    - rclone sync public scaleway-ams:lioman.de --checksum --progress
  only:
    - main
