# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/pelican
image: python:3.8

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - pip install poetry
  - poetry install
  - curl -o /usr/local/bin/stork https://files.stork-search.net/releases/v1.4.0/stork-ubuntu-20-04
  - chmod +x /usr/local/bin/stork

test-build:
  script:
    - poetry run invoke build
  except:
    - master
    - main

pages:
  script:
    - poetry run invoke publish
  artifacts:
    paths:
      - public/
  only:
    - master
    - main
