# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile
tasks:
  - name: "install dependencies and start live server"
    env:
      PIP_USER: false
    before: eval $(gp env -e)
    init:  poetry install
    command: poetry run invoke livereload
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8001
    onOpen: open-preview
