[tool.poetry]
name = "blog"
version = "0.1.0"
description = "lioman.de blog"
authors = ["Elias Kirchgässner <blog@lioman.de>"]
license = "CC-BY-SA-4.0"

[tool.poetry.dependencies]
python = "^3.10"
pelican = "^4.8.0"
typogrify = "^2.0.7"
pelican-youtube = "^0.2.0"
pelican-vimeo = "^0.1.1"
pillow = "^8.1.1"
pelican-extended-sitemap = "^1.2.3"
bs4 = "^0.0.1"
markdown = "^3.2.1"
invoke = "^1.4.1"
pelican-series = "^2.1.0"
pelican-neighbors = "^1.2.0"
pelican-precompress = "^1.1.2"
zopfli = "^0.1.7"
Brotli = "^1.0.9"
pelican-search = {git = "https://github.com/lioman/search", rev = "main"}
pelican-i18n-templates = {path = "plugins/i18n_templates"}

[tool.poetry.dev-dependencies]
black = "^22.3.0"
livereload = "^2.6.3"
python-slugify = "^6.1.2"

[tool.poetry.scripts]
build = "pelican -s publishconf.py"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
