---
- hosts: blog
  become: true
  become_method: sudo
  roles:
    - role: caddy-ansible
      caddy_setcap: yes
      caddy_config: |
        www.lioman.de
        gzip

        tls blog@lioman.de

        root /var/www/lioman.de
