---
- hosts: blog
  become: true
  become_method: sudo
  vars:
    nginx_ppa_use: true
    nginx_ppa_version: stable
    nginx_remove_default_vhost: true
    nginx_vhosts:
    #- listen: "443 ssl http2"
    - listen: "80"
      server_name: "www.lioman.de"
      #server_name_redirect: "lioman.de"
      root: "/var/www/lioman.de"
      index: "index.html index.htm"
      error_page: "404 /404.html"
      state: "present"
      filename: "lioman.de.conf"
#      extra_parameters: |
#        ssl_certificate     /etc/ssl/certs/ssl-cert-snakeoil.pem;
#        ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
#        ssl_protocols       TLSv1.1 TLSv1.2;
#        ssl_ciphers         HIGH:!aNULL:!MD5;
  tasks:
    - name: "add let's encrypt repository"
      apt_repository:
        repo: 'ppa:certbot/certbot'
    - name: "install certbot"
      apt:
        name: python-certbot-nginx
  roles:
    - { role: geerlingguy.nginx }
